# Generated by Django 4.2.5 on 2023-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_sttmodel_ttsmodel_remove_speechmodel_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttmodel',
            name='audio',
            field=models.FileField(default=None, upload_to='stt'),
        ),
        migrations.AlterField(
            model_name='ttsmodel',
            name='audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tts'),
        ),
    ]
